import React,{useEffect,useRef,useState} from 'react';
import {BarChart3,Check,Heart,ListChecks,Settings2,X} from 'lucide-react';
import {dateLabel,number} from './model';
export function IconButton({label,children,...props}){return <button type="button" className="icon-button" aria-label={label} title={label} {...props}>{children}</button>;}
export function Heading({title,sub,action}){return <div className="section-heading"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>;}
export function Modal({title,onClose,children}){const ref=useRef();useEffect(()=>{const previous=document.activeElement,el=ref.current;el.showModal();return()=>{el.close();previous?.focus();};},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}} aria-labelledby="modal-title"><div className="modal-content"><header><h2 id="modal-title">{title}</h2><IconButton label="Close" onClick={onClose}><X/></IconButton></header>{children}<button className="primary full" onClick={onClose}>Done</button></div></dialog>;}
export function MiniChart({series,color}){const max=Math.max(1,...series.map(x=>x.value||0));return <div className="mini-chart" aria-hidden="true">{series.map(x=><i key={x.date} className={x.value===null?'missing':''} style={{height:x.value===null?3:`${Math.max(4,x.value/max*100)}%`,background:color,maxHeight:'none'}}/>)}</div>;}
export function Rings({water,habits,tasks}){return <svg className="rings" viewBox="0 0 144 144" role="img" aria-label={`Water goal ${Math.round(water*100)}%, habits ${Math.round(habits*100)}%, checklist ${Math.round(tasks*100)}%`}><g transform="rotate(-90 72 72)">{[water,habits,tasks].map((v,i)=>{const r=60-i*17,c=2*Math.PI*r;return <g key={i} style={{color:['#ff6087','#b7ed51','#4dd7e8'][i]}}><circle cx="72" cy="72" r={r} stroke="currentColor" opacity=".13" fill="none" strokeWidth="12"/><circle cx="72" cy="72" r={r} stroke="currentColor" fill="none" strokeWidth="12" strokeLinecap="round" strokeDasharray={`${c*Math.min(1,v)} ${c}`}/></g>;})}</g><Heart x="61" y="61" width="22" height="22" fill="currentColor" strokeWidth="0"/></svg>;}
export function TrendChart({series,meta,currency,goal}){
 const [selected,setSelected]=useState(null);useEffect(()=>setSelected(null),[meta.name,series.length,series.at(-1)?.date]);
 const max=Math.max(goal||0,...series.map(x=>x.value||0),1),values=series.filter(x=>x.value!==null),chosen=selected!==null?series[selected]:null,unit=meta.name==='Spending'?currency:meta.unit;
 return <div className="trend-chart" style={{'--metric':meta.color}}><div className="chart-readout" aria-live="polite">{chosen?<><b>{chosen.value===null?'Not logged':`${number(chosen.value)} ${unit}`}</b><span>{dateLabel(chosen.date,{weekday:'short',month:'short',day:'numeric'})}</span></>:<><b>{values.length?`${values.length} days logged`:'No entries in this period'}</b><span>{values.length?'Tap a bar to inspect a day':'Start logging to see your own trends.'}</span></>}</div><div className="plot-wrap"><div className="y-axis"><span>{number(max)}</span><span>{number(max/2)}</span><span>0</span></div><div className="plot">{[0,50,100].map(v=><div key={v} className="grid-line" style={{bottom:`${v}%`}}/>)}{goal>0&&<div className="goal-line" style={{bottom:`${goal/max*100}%`}}><span>Goal {number(goal)}</span></div>}<div className="bars">{series.map((x,i)=><button key={x.date} className={`bar-slot ${selected===i?'selected':''}`} onClick={()=>setSelected(i)} aria-label={`${dateLabel(x.date)}: ${x.value===null?'not logged':number(x.value)+' '+unit}`}><span className={x.value===null?'unlogged':''} style={{height:x.value===null?3:`${Math.max(1.5,x.value/max*100)}%`}}/></button>)}</div></div></div><div className="x-axis"><span>{dateLabel(series[0].date)}</span><span>{dateLabel(series[Math.floor(series.length/2)].date)}</span><span>{dateLabel(series.at(-1).date)}</span></div></div>;
}
export function GoalField({label,value,min,max,step,onChange}){const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);return <label className="field goal-field">{label}<input type="number" inputMode="decimal" min={min} max={max} step={step} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{const n=Number(draft);if(draft!==''&&Number.isFinite(n)&&n>=min&&n<=max){const v=Math.round(n/step)*step;onChange(v);setDraft(String(v));}else setDraft(String(value));}}/></label>;}
export function Navigation({tab,setTab}){return <>{[['summary','Summary',Heart],['daily','Daily',ListChecks],['trends','Trends',BarChart3],['settings','Settings',Settings2]].map(([key,label,Icon])=><button key={key} aria-current={tab===key?'page':undefined} className={tab===key?'active':''} onClick={()=>{setTab(key);window.scrollTo({top:0,behavior:'smooth'});}}><Icon size={21}/><span>{label}</span></button>)}</>;}
