import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowDown,ArrowUp,BarChart3,BookOpen,Check,ChevronLeft,ChevronRight,Download,Droplets,Dumbbell,Flame,Heart,Minus,Moon,Pause,Play,Plus,RotateCcw,Settings2,Smile,Timer,Trash2,Utensils,Wallet,X} from 'lucide-react';
import {DATA_KEY,SETTINGS_KEY,defaultSettings,dateKey,shiftDate,dateLabel,blankDay,loadData,metricValue,seriesFor,streakFor,average,number} from './model';
import {IconButton,Heading,Modal,MiniChart,Rings,TrendChart,GoalField,Navigation} from './components';
import './styles.css';
if('serviceWorker' in navigator&&import.meta.env.PROD)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
const METRICS={water:{name:'Water',color:'#40b8ff',icon:Droplets,unit:'ml',goal:'waterGoal'},sleep:{name:'Sleep',color:'#a28aff',icon:Moon,unit:'hrs',goal:'sleepGoal'},workout:{name:'Workouts',color:'#b7ed51',icon:Dumbbell,unit:'sessions'},mood:{name:'State of mind',color:'#68dcc6',icon:Smile,unit:''},meals:{name:'Nutrition',color:'#ffab58',icon:Utensils,unit:'meals',goal:'mealGoal'},spending:{name:'Spending',color:'#ff839e',icon:Wallet,unit:''},habits:{name:'Habits',color:'#ffd269',icon:Flame,unit:'%'},focus:{name:'Focus',color:'#7eb9ff',icon:Timer,unit:'min'}};
const moods=[['Focused','In the zone'],['Calm','At ease'],['Stressed','Under pressure']];
const clock=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function App(){
 const [initial]=useState(()=>{try{return {data:loadData(),error:null};}catch{return {data:{},error:'Saved entries could not be read. Export your raw backup before making new entries.'};}});
 const [data,setData]=useState(initial.data),[storageError,setStorageError]=useState(initial.error);
 const [settings,setSettings]=useState(()=>{try{return {...defaultSettings,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')};}catch{return defaultSettings;}});
 const [tab,setTab]=useState('summary'),[date,setDate]=useState(dateKey()),[now,setNow]=useState(new Date()),[modal,setModal]=useState(null);
 const [task,setTask]=useState(''),[meal,setMeal]=useState(''),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[newHabit,setNewHabit]=useState('');
 const [metric,setMetric]=useState('water'),[range,setRange]=useState(7),[notice,setNotice]=useState('');
 const [timer,setTimer]=useState(()=>{try{return JSON.parse(localStorage.getItem('life-os-timer-v2'))||{remaining:settings.focusMinutes*60,end:null,total:settings.focusMinutes*60};}catch{return {remaining:settings.focusMinutes*60,end:null,total:settings.focusMinutes*60};}});
 const day=data[date]||blankDay(),today=dateKey(now),timerSeconds=timer.end?Math.max(0,Math.ceil((timer.end-now.getTime())/1000)):timer.remaining;
 useEffect(()=>{const id=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(id);},[]);
 useEffect(()=>{document.documentElement.dataset.theme=settings.theme;document.documentElement.dataset.accent=settings.accent;try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch{setStorageError('Storage is full or unavailable. Export a backup to keep your entries.');}},[settings]);
 useEffect(()=>{if(initial.error)return;try{localStorage.setItem(DATA_KEY,JSON.stringify(data));setStorageError(null);}catch{setStorageError('Entries could not be saved. Keep this page open and export a backup.');}},[data]);
 useEffect(()=>{try{localStorage.setItem('life-os-timer-v2',JSON.stringify(timer));}catch{}},[timer]);
 useEffect(()=>{if(timer.end&&timerSeconds===0&&!initial.error){const key=timer.date||today;setData(prev=>{const d=prev[key]||blankDay();return {...prev,[key]:{...d,focusMinutes:d.focusMinutes+timer.total/60,logged:{...d.logged,focus:true}}};});setTimer(t=>({...t,end:null,remaining:0}));setNotice('Focus session complete. Your minutes have been saved.');}},[timerSeconds,timer.end]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(id);},[notice]);
 const update=fn=>{if(initial.error){setNotice('Saved data could not be read. Export your raw backup first.');return;}setData(prev=>({...prev,[date]:fn(prev[date]||blankDay())}));};
 const health=(patch,field)=>update(d=>({...d,health:{...d.health,...patch},logged:{...d.logged,[field]:true}}));
 const pref=(key,value)=>setSettings(s=>({...s,[key]:value}));
 const toggleHabit=id=>update(d=>({...d,habitTargetIds:settings.habits.map(h=>h.id),habits:{...d.habits,[id]:!d.habits[id]},logged:{...d.logged,habits:true}}));
 const unit=key=>key==='spending'?settings.currency:METRICS[key].unit;
 const done=day.tasks.filter(t=>t.done).length,habitDone=settings.habits.filter(h=>day.habits[h.id]).length;
 const habitRatio=settings.habits.length?habitDone/settings.habits.length:0,taskRatio=day.tasks.length?done/day.tasks.length:0,waterRatio=Math.min(1,day.health.water/settings.waterGoal);
 const changeDate=key=>{if(key&&/^\d{4}-\d{2}-\d{2}$/.test(key)&&key<=today)setDate(key);};
 const week=Array.from({length:7},(_,i)=>shiftDate(date,i-6));
 const openMetric=key=>{setModal(key);setMeal('');setAmount('');setNote('');};
 const exportData=()=>{const content=initial.error?{raw:localStorage.getItem(DATA_KEY)}:{version:2,exportedAt:new Date().toISOString(),data,settings};const url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`life-os-backup-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const allSeries=seriesFor(data,date,range,metric,settings),mean=average(allSeries),prevMean=average(seriesFor(data,shiftDate(date,-range),range,metric,settings));
 const delta=mean!==null&&prevMean!==null?mean-prevMean:null;
 const displayValue=key=>{if(key==='mood')return day.mental.mood||'Not logged';const v=metricValue(data[date],key,settings);return v===null?'—':number(v);};
 const editCards=()=>setTab('settings');
 const addExpense=e=>{e.preventDefault();const n=Number(amount);if(!Number.isFinite(n)||n<=0||n>1e9)return;update(d=>{const expenses=[...d.finance.expenses,{id:crypto.randomUUID(),amount:Math.round(n*100)/100,note:note.trim()||'Expense'}];return {...d,finance:{spent:expenses.reduce((s,x)=>s+x.amount,0),expenses},logged:{...d.logged,spending:true}};});setAmount('');setNote('');};
 const title={summary:'Summary',daily:'Your day',trends:'Trends',settings:'Make it yours'}[tab];
 return <div className="app"><aside className="sidebar"><a href="#" className="brand" onClick={e=>{e.preventDefault();setTab('summary');}}><span><Heart fill="currentColor"/></span>Life OS<span className="brand-dot">.</span></a><p className="sidebar-label">YOUR PERSONAL SPACE</p><Navigation tab={tab} setTab={setTab}/><div className="sidebar-footer"><div className="avatar">{settings.name.slice(0,1).toUpperCase()||'Y'}</div><div><b>{settings.name||'Your space'}</b><small>One day at a time.</small></div></div></aside>
 <main className="main"><header className="page-header"><div><p className="eyebrow">{dateLabel(today,{weekday:'long',month:'long',day:'numeric'})} <span>· {now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></p><h1>{title}<span className="title-dot">.</span></h1></div><button className="profile" aria-label="Open settings" onClick={()=>setTab('settings')}>{settings.name.slice(0,1).toUpperCase()||<Settings2/>}</button></header>
 {storageError&&<div className="warning" role="alert">{storageError} <button onClick={exportData}>Export backup</button></div>}
 {tab!=='settings'&&<div className="date-toolbar"><div className="date-control"><IconButton label="Previous week" onClick={()=>changeDate(shiftDate(date,-7))}><ChevronLeft size={18}/></IconButton><label className="date-input"><input aria-label="Selected date" type="date" value={date} max={today} onChange={e=>changeDate(e.target.value)}/></label><IconButton label="Next week" disabled={date===today} onClick={()=>changeDate(shiftDate(date,7)>today?today:shiftDate(date,7))}><ChevronRight size={18}/></IconButton></div><button className="text-button" onClick={()=>setDate(today)}>{date===today?'Today':'Back to today'}</button></div>}
 {tab==='summary'&&<>
 <div className="welcome"><span className="tiny-heart"><Heart size={15} fill="currentColor"/></span><span>Your health. Your rhythm.</span><span className="local-badge">ON THIS DEVICE</span></div>
 <section className="activity-card"><div><div className="card-label pink"><Activity size={18}/>Daily activity</div><h2>A little better,<br/>every day.</h2><p>{date===today?`Your daily snapshot, ${settings.name||'just for you'}.`:dateLabel(date,{weekday:'long',month:'long',day:'numeric'})}</p><div className="ring-legend"><span><i className="pink-bg"/>{Math.round(waterRatio*100)}% water</span><span><i className="lime-bg"/>{habitDone}/{settings.habits.length} habits</span><span><i className="teal-bg"/>{done}/{day.tasks.length} tasks</span></div></div><Rings water={waterRatio} habits={habitRatio} tasks={taskRatio}/></section>
 <Heading title="Favourites" sub="The things that matter to you." action={<button className="text-button" onClick={editCards}>Edit</button>}/>
 <div className="metric-grid">{settings.cards.map(key=>{const m=METRICS[key],Icon=m.icon;return <button key={key} className={`metric-card metric-${key}`} style={{'--metric':m.color}} onClick={()=>openMetric(key)}><div className="metric-card-head"><span><Icon size={18}/>{m.name}</span><ChevronRight size={16}/></div><div className="metric-middle"><div><strong className={key==='mood'?'mood-value':''}>{displayValue(key)}</strong>{key!=='mood'&&<small>{unit(key)}</small>}</div>{key==='mood'?<div className={`mood-orb ${day.mental.mood?.toLowerCase()||''}`}><Smile size={27}/></div>:<MiniChart color={m.color} series={seriesFor(data,date,7,key,settings)}/>}</div><div className="metric-foot">{m.goal?`Daily goal: ${number(settings[m.goal])} ${m.unit}`:key==='mood'?'Take a moment to check in':key==='workout'?(day.health.workout?'You showed up. Well done.':'Movement, at your own pace.'):'Tap to add or edit'}<span>{date===today?'Today':dateLabel(date)}</span></div></button>;})}</div>
 {!settings.cards.length&&<div className="empty panel">Choose your favourite cards in Settings.<button className="text-button" onClick={editCards}>Choose cards</button></div>}
 <Heading title="A bigger picture" sub="Small entries become useful insights."/><button className="insight-card panel" onClick={()=>setTab('trends')}><span className="insight-icon"><BarChart3/></span><div><h3>Your patterns, over time</h3><p>Explore water, sleep, movement and more across 7, 30 or 90 days.</p><span className="text-link">Explore trends <ChevronRight size={14}/></span></div></button>
 </>}
 {tab==='daily'&&<><div className="week-row">{week.map(k=><button key={k} className={date===k?'active':''} onClick={()=>changeDate(k)}><span>{dateLabel(k,{weekday:'short'})}</span><b>{dateLabel(k,{day:'numeric'})}</b><i className={data[k]?'has-data':''}/></button>)}</div><div className="daily-grid">
 <section className="panel"><Heading title="Checklist" sub={`${done} of ${day.tasks.length} complete`}/>{!day.tasks.length&&<p className="empty-inline">A clear day starts with one small intention.</p>}<div className="list">{day.tasks.map(t=><div className="list-row" key={t.id}><button className={`check-row ${t.done?'checked':''}`} aria-pressed={t.done} onClick={()=>update(d=>({...d,tasks:d.tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x)}))}><span className="checkbox">{t.done&&<Check size={15}/>}</span><span>{t.text}</span></button><IconButton label={`Delete ${t.text}`} onClick={()=>update(d=>({...d,tasks:d.tasks.filter(x=>x.id!==t.id)}))}><Trash2 size={16}/></IconButton></div>)}</div><form className="add-form" onSubmit={e=>{e.preventDefault();if(!task.trim())return;update(d=>({...d,tasks:[...d.tasks,{id:crypto.randomUUID(),text:task.trim(),done:false}]}));setTask('');}}><input aria-label="New task" value={task} maxLength={180} onChange={e=>setTask(e.target.value)} placeholder="Add an intention"/><IconButton label="Add task" type="submit"><Plus size={20}/></IconButton></form></section>
 <section className="panel"><Heading title="Daily habits" sub="Consistency over perfection." action={<button className="text-button" onClick={editCards}>Edit</button>}/>{!settings.habits.length&&<p className="empty-inline">Add a personal habit in Settings.</p>}{settings.habits.map(h=><button className={`habit-row ${day.habits[h.id]?'checked':''}`} key={h.id} aria-pressed={!!day.habits[h.id]} onClick={()=>toggleHabit(h.id)}><span className="habit-icon"><BookOpen size={19}/></span><span className="habit-name">{h.name}<small><Flame size={12}/> {streakFor(data,date,h.id)} day streak</small></span><span className="checkbox">{day.habits[h.id]&&<Check size={15}/>}</span></button>)}</section>
 <section className="panel focus-panel"><div className="card-label blue"><Timer size={19}/>Focus time</div><p className="focus-subtitle">One thing deserves your full attention.</p><div className="focus-clock">{clock(timerSeconds)}</div><p className="focus-status">{timer.end?'Session in progress':timerSeconds===0?'Session complete':'Find your flow'}</p><div className="focus-controls"><button className="primary" disabled={date!==today&&!timer.end} onClick={()=>setTimer(t=>t.end?{...t,remaining:timerSeconds,end:null}:timerSeconds===0?{remaining:settings.focusMinutes*60,total:settings.focusMinutes*60,end:Date.now()+settings.focusMinutes*60000,date:today}:{...t,end:Date.now()+t.remaining*1000,date:t.date||today})}>{timer.end?<Pause size={17}/>:<Play size={17}/>} {timer.end?'Pause':'Start focus'}</button><IconButton label="Reset focus timer" onClick={()=>setTimer({remaining:settings.focusMinutes*60,total:settings.focusMinutes*60,end:null})}><RotateCcw size={19}/></IconButton></div><p className="small-note">{number(day.focusMinutes)} min completed · {date!==today?'Return to today to start a session.':`${settings.focusMinutes} minute sessions`}</p></section>
 <section className="panel"><Heading title="Quick check-in" sub="Keep your day up to date."/><div className="quick-grid">{Object.entries(METRICS).filter(([k])=>!['habits','focus'].includes(k)).map(([key,m])=>{const Icon=m.icon;return <button key={key} onClick={()=>openMetric(key)} style={{'--metric':m.color}}><Icon size={21}/><span>{m.name}</span><Plus size={15}/></button>;})}</div></section>
 </div></>}
 {tab==='trends'&&<><p className="page-intro">See the patterns behind your everyday choices.</p><div className="trend-metrics" role="group" aria-label="Trend metric">{Object.entries(METRICS).filter(([k])=>k!=='mood').map(([key,m])=>{const Icon=m.icon;return <button key={key} onClick={()=>setMetric(key)} className={metric===key?'active':''}><Icon size={17}/>{m.name}</button>;})}</div><section className="panel trend-panel"><div className="trend-heading"><div className="card-label" style={{color:METRICS[metric].color}}>{React.createElement(METRICS[metric].icon,{size:19})}{METRICS[metric].name}</div><div className="segmented" aria-label="Chart period">{[7,30,90].map(n=><button key={n} className={n===range?'active':''} onClick={()=>setRange(n)}>{n}D</button>)}</div></div><p className="overline">DAILY AVERAGE · LOGGED DAYS</p><div className="trend-number">{mean===null?'—':number(mean)}<span>{unit(metric)}</span></div><p className="muted">{dateLabel(allSeries[0].date)} – {dateLabel(date,{month:'short',day:'numeric',year:'numeric'})}</p><TrendChart series={allSeries} meta={METRICS[metric]} currency={settings.currency} goal={METRICS[metric].goal?settings[METRICS[metric].goal]:metric==='habits'?100:0}/></section><div className="trend-facts"><section className="panel"><span className="overline">PREVIOUS {range} DAYS</span><h3>{delta===null?'More history needed':`${delta>0?'+':''}${number(delta)} ${unit(metric)}`}</h3><p>{delta===null?'A comparison appears when both periods have entries.':'Change in daily average versus the preceding period.'}</p></section><section className="panel"><span className="overline">YOUR DATA</span><h3>{allSeries.filter(x=>x.value!==null).length} of {range} days</h3><p>Missing days stay empty and are excluded from averages.</p></section></div>{Object.values(data).some(d=>d.legacy)&&<p className="small-note">Earlier app entries may include prefilled sleep and mood values. Review those dates if they were not logged by you.</p>}<Heading title="Daily records" sub="Select a date to review or correct it."/><div className="panel records">{allSeries.filter(x=>x.value!==null).reverse().map(x=><button key={x.date} onClick={()=>{setDate(x.date);['habits','focus'].includes(metric)?setTab('daily'):openMetric(metric);}}><span>{dateLabel(x.date,{weekday:'short',month:'short',day:'numeric'})}</span><b>{number(x.value)} <small>{unit(metric)}</small></b><ChevronRight size={16}/></button>)}{!allSeries.some(x=>x.value!==null)&&<p className="empty-inline">No records yet. Add your first entry from Summary.</p>}</div></>}
 {tab==='settings'&&<><p className="page-intro">A dashboard that fits your life.</p><div className="settings-grid"><section className="panel"><Heading title="Personalise"/><label className="field">Your name<input value={settings.name} maxLength={30} onChange={e=>pref('name',e.target.value)}/></label><label className="field">Currency<select value={settings.currency} onChange={e=>pref('currency',e.target.value)}>{['LKR','USD','GBP','EUR','INR','AUD'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Appearance<select value={settings.theme} onChange={e=>pref('theme',e.target.value)}><option value="dark">AMOLED dark</option><option value="light">Clean light</option></select></label><div className="field">Accent colour<div className="swatches">{[['blue','#579aff'],['purple','#a28aff'],['pink','#ff6087'],['teal','#42c7b4']].map(([key,color])=><button key={key} aria-label={`${key} accent`} aria-pressed={settings.accent===key} style={{background:color}} onClick={()=>pref('accent',key)}>{settings.accent===key&&<Check size={18}/>}</button>)}</div></div></section>
 <section className="panel"><Heading title="Daily goals" sub="Set targets that work for you."/>{[['waterGoal','Water (ml)',250,10000,250],['sleepGoal','Sleep (hours)',1,12,.5],['mealGoal','Meals',1,12,1],['focusMinutes','Focus session (minutes)',1,120,1]].map(([key,label,min,max,step])=><GoalField key={key} label={label} value={settings[key]} min={min} max={max} step={step} onChange={value=>{pref(key,value);if(key==='focusMinutes'&&!timer.end)setTimer({remaining:value*60,total:value*60,end:null});}}/>)}</section>
 <section className="panel"><Heading title="Favourite cards" sub="Show, hide and reorder your summary."/>{[...settings.cards,...defaultSettings.cards.filter(k=>!settings.cards.includes(k))].map(key=>{const m=METRICS[key],idx=settings.cards.indexOf(key);return <div className="favourite-row" key={key}><button aria-pressed={idx>=0} onClick={()=>pref('cards',idx<0?[...settings.cards,key]:settings.cards.filter(k=>k!==key))}><span className={`checkbox ${idx>=0?'is-checked':''}`}>{idx>=0&&<Check size={14}/>}</span>{m.name}</button><div><IconButton label={`Move ${m.name} up`} disabled={idx<=0} onClick={()=>{const a=[...settings.cards];[a[idx-1],a[idx]]=[a[idx],a[idx-1]];pref('cards',a);}}><ArrowUp size={16}/></IconButton><IconButton label={`Move ${m.name} down`} disabled={idx<0||idx===settings.cards.length-1} onClick={()=>{const a=[...settings.cards];[a[idx+1],a[idx]]=[a[idx],a[idx+1]];pref('cards',a);}}><ArrowDown size={16}/></IconButton></div></div>;})}</section>
 <section className="panel"><Heading title="Your habits" sub="Rename or add your own daily goals."/>{settings.habits.map(h=><div className="habit-edit" key={h.id}><input aria-label={`Habit name ${h.name}`} value={h.name} maxLength={60} onChange={e=>pref('habits',settings.habits.map(x=>x.id===h.id?{...x,name:e.target.value}:x))}/><IconButton label={`Remove habit ${h.name}`} onClick={()=>{pref('habits',settings.habits.filter(x=>x.id!==h.id));setNotice('Habit removed from your list. Its past records are kept.');}}><X size={17}/></IconButton></div>)}<form className="add-form" onSubmit={e=>{e.preventDefault();if(!newHabit.trim())return;pref('habits',[...settings.habits,{id:crypto.randomUUID(),name:newHabit.trim()}]);setNewHabit('');}}><input aria-label="New habit" placeholder="e.g. Walk outside" value={newHabit} maxLength={60} onChange={e=>setNewHabit(e.target.value)}/><IconButton type="submit" label="Add habit"><Plus size={20}/></IconButton></form></section></div><section className="panel backup-panel"><div><h3>Your data stays with you.</h3><p>Saved in this browser, on this device. Export a backup before clearing browser data. Entries do not sync between devices.</p></div><button className="secondary" onClick={exportData}><Download size={18}/>Export backup</button></section></>}
 <footer className="page-footer"><Heart size={12}/>Made for your everyday.</footer>
 </main><nav className="bottom-nav" aria-label="Main navigation"><Navigation tab={tab} setTab={setTab}/></nav>
 {notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
 {modal&&<Modal title={METRICS[modal].name} onClose={()=>setModal(null)}><p className="modal-date">{dateLabel(date,{weekday:'long',month:'long',day:'numeric'})}</p>
 {modal==='water'&&<><div className="log-hero blue"><Droplets size={32}/><strong>{number(day.health.water)}<small> ml</small></strong><p>of {number(settings.waterGoal)} ml daily goal</p></div><div className="water-track"><i style={{width:`${waterRatio*100}%`}}/></div><div className="stepper"><button className="secondary" disabled={!day.health.water} onClick={()=>health({water:Math.max(0,day.health.water-250)},'water')}><Minus size={18}/>250 ml</button><button className="primary" disabled={day.health.water>=20000} onClick={()=>health({water:Math.min(20000,day.health.water+250)},'water')}><Plus size={18}/>250 ml</button></div><GoalField label="Correct total (ml)" value={day.health.water} min={0} max={20000} step={1} onChange={v=>health({water:v},'water')}/></>}
 {modal==='sleep'&&<><div className="log-hero purple"><Moon size={32}/><strong>{day.health.sleep===null?'—':number(day.health.sleep)}<small> hrs</small></strong><p>Daily goal: {settings.sleepGoal} hours</p></div><label className="field">Hours slept<input aria-label="Hours slept" type="range" min="0" max="12" step="0.5" value={day.health.sleep??0} onChange={e=>health({sleep:Number(e.target.value)},'sleep')}/></label><div className="range-labels"><span>0 hrs</span><span>12 hrs</span></div><GoalField label="Exact hours" value={day.health.sleep??0} min={0} max={12} step={0.25} onChange={v=>health({sleep:v},'sleep')}/></>}
 {modal==='workout'&&<><div className="workout-choice"><button className={day.logged.workout&&day.health.workout?'active':''} onClick={()=>health({workout:true},'workout')}><Dumbbell/>Workout complete</button><button className={day.logged.workout&&!day.health.workout?'active':''} onClick={()=>health({workout:false},'workout')}><Moon/>Rest day</button></div><label className="field">Routine / notes<textarea value={day.health.workoutLog} maxLength={2000} onChange={e=>health({workoutLog:e.target.value},'workout')} placeholder="Exercises, sets, or how you felt…"/></label></>}
 {modal==='mood'&&<><p className="modal-prompt">How are you feeling?</p><div className="mood-options">{moods.map(([m,desc])=><button key={m} aria-pressed={day.mental.mood===m} className={day.mental.mood===m?'active':''} onClick={()=>update(d=>({...d,mental:{mood:m},logged:{...d.logged,mood:true}}))}><span className={`mood-orb ${m.toLowerCase()}`}><Smile/></span><b>{m}</b><small>{desc}</small></button>)}</div><p className="small-note">No right answer. Just a moment to notice.</p></>}
 {modal==='meals'&&<><p className="modal-prompt">{day.health.meals.length} of {settings.mealGoal} meals logged</p><form className="add-form" onSubmit={e=>{e.preventDefault();if(!meal.trim())return;health({meals:[...day.health.meals,meal.trim()]},'meals');setMeal('');}}><input aria-label="Meal description" value={meal} maxLength={150} onChange={e=>setMeal(e.target.value)} placeholder="Breakfast · oats and eggs"/><IconButton label="Add meal" type="submit"><Plus/></IconButton></form><div className="entry-list">{day.health.meals.map((m,i)=><div key={i}><span><Utensils size={17}/>{m}</span><IconButton label={`Delete meal ${m}`} onClick={()=>health({meals:day.health.meals.filter((_,j)=>i!==j)},'meals')}><Trash2 size={16}/></IconButton></div>)}</div></>}
 {modal==='spending'&&<><div className="log-hero pink"><Wallet size={30}/><strong>{number(day.finance.expenses.reduce((s,x)=>s+x.amount,0))}<small> {settings.currency}</small></strong></div><form onSubmit={addExpense}><label className="field">Amount ({settings.currency})<input aria-label="Expense amount" required type="number" inputMode="decimal" min="0.01" max="1000000000" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></label><label className="field">What was it for?<input value={note} maxLength={150} onChange={e=>setNote(e.target.value)} placeholder="Lunch, transport…"/></label><button className="secondary full" type="submit"><Plus size={17}/>Add expense</button></form><div className="entry-list">{day.finance.expenses.map(x=><div key={x.id}><span>{x.note}<small>{number(x.amount)} {settings.currency}</small></span><IconButton label={`Delete expense ${x.note}`} onClick={()=>update(d=>{const expenses=d.finance.expenses.filter(e=>e.id!==x.id);return {...d,finance:{spent:expenses.reduce((s,e)=>s+e.amount,0),expenses}};})}><Trash2 size={16}/></IconButton></div>)}</div></>}
 {modal!=='mood'&&<button className="text-button view-trend" onClick={()=>{setMetric(modal);setTab('trends');setModal(null);}}>View {METRICS[modal].name.toLowerCase()} trends <ChevronRight size={15}/></button>}
 </Modal>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
